version: "3.7"
services:
  hyphen:
    image: hyphen
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        PYTHON_VERSION: 3.11
        ENVIRONMENT: development
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./tests:/app/tests
      - ./hyphen:/app/hyphen
      - ./.pytest_cache:/app/.pytest_cache
      - ./pytest.ini:/app/pytest.ini
      - ./prospector.yml:/app/prospector.yml

  docs:
    hostname: docs
    image: docs
    build:
      context: .
      dockerfile: dockerfiles/docs.Dockerfile
    volumes:
      - ./docs:/docs
      - ./hyphen:/package_src/hyphen
    environment:
      - PYTHONPATH=/package_src
    ports:
      - "8000:8000"
  publish:
    profiles: ["publish"]
    image: hyphen
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        PYTHON_VERSION: 3.6
        ENVIRONMENT: development
    volumes:
      - .:/app

    command: python3 -m build && python3 -m twine upload --repository testpypi dist/*

networks:
  default:
    name: hyphen
    external: true