version: "3.7"
services:
  hyphen:
    image: hyphen
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11
        ENVIRONMENT: development
    env_file:
      - .env
    volumes:
      - ./tests:/app/tests
      - ./hyphen:/app/hyphen

  docs:
    profiles:  ["disabled"]
    hostname: docs
    image: ethanknox/docula:0.3.7
    volumes:
      - ./docs:/docs
    command: --serve --watch --port=8081
    ports:
      - "8081:8081"

  publish:
    profiles: ["publish"]
    image: hyphen
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.6
        ENVIRONMENT: development
    volumes:
      - .:/app
    command: python3 -m build && python3 -m twine upload --repository testpypi dist/*
